module.exports = {
"plank":  "Start by getting into a press up position. Bend your elbows and rest your weight ono your forearms and not on your hands. Your body should form a straight line from shoulders to ankles. Engage your core by sucking your belly button into your spine.",
"squats":  "Stand tall with your feet hip width apart and your arms down by your side. Start to lower your body back as far as you can by pushing your hips back and bending your knees and pushing your body weight into your heels. As you are lowering into the squat your arms will start to raise out in front of you for balance. The lower body should be parallel with the floor and your chest should be lifted at all times not rounded. Pause then lift back up in a controlled movement to the starting position.",
"push-ups":  "Lie on the floor face down and place your hands shoulder width apart while holding your torso up at arms length. Next, lower yourself downward until your chest almost touches the floor as you inhale. Now breathe out and press your upper body back up to the starting position while squeezing your chest. After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.",
"tricep dips":  "Hands should be shoulder width apart fingers facing forward and elbows pointing backwards with a slight bend in the elbows. Legs extended out in front of you with a slight bend in the knee. Slowly lower your body until your shoulder joints are below your elbows. Push back up until your elbows are nearly straight but do not lock them out.",
"lunges":  "Keep your upper body straight, with your shoulders back and relaxed and chin up (pick a point to stare at in front of you so you don't keep looking down). Always engage your core. Step forward with one leg, lowering your hips until both knees are bent at about a 90-degree angle. Make sure your front knee is directly above your ankle, not pushed out too far, and make sure your other knee doesn't touch the floor. Keep the weight in your heels as you push back up to the starting position.",
"burpees":  "Stand with your feet hip width apart and your arms down by your side. Lower into a squat position with your hands flat on the floor in front of you. Kick your legs backwards into a press up position and lower your chest to the floor. Push your chest back up to the press up position thrust both feet forward so you are back in the squat position. Jump up and raise both hands over your head.",
"wall sits":  "Start by standing about 2 feet away from a wall with your back against the wall. Slide your back down the wall until your hips and knees bend at a 90 degrees angle. Keep the shoulders, upper back and the back of the head against the wall. Both feet should be flat on the ground with the weight evenly distributed. Hold for the required amount of time.",
"jumping jacks":  "Stand with your feet together and your hands down by your side. In one motion jump your feet out to the side and raise your arms above your head. Immediately reverse that motion by jumping back to the starting position.",
"bicycle crunches":  "Lie flat on the floor with the lower back pressed into the ground. Place your hands slightly either side of your head, do not lock your fingers or pull the head up. Lift your knees to a 45 degree angle. At first slowly go through a bicycle pedal motion with the legs. Alternately touching your elbows to the opposite knee twisting back and forth through the core, keep the elbows back rather than forward to the chest as this could strain the neck.",
"step-ups":  "To start, place your entire right foot onto the bench or chair. Press through your right heel as you step onto the bench, bringing your left foot to meet your left so you are standing on the bench. Return to the starting position by stepping down with the right foot, then the left so both feet are on the floor. Repeat as required.",
"high knees":  "Stand straight with the feet hip width apart, looking straight ahead and arms hanging down by your side. Jump from one foot to the other at the same time lifting your knees as high as possible, hip height is advisable. The arms should be following the motion. Touch the ground with the balls of your feet.",
}; 
